cache:
  paths:
    - node_modules

pages:
  image: node:12-alpine
  script:
    - npm install
    - npm run build
    - npm run export
    - mv public public_
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master

# deploys3:
#   image: "python:latest" # We use python because there is a well-working AWS Sdk
#   stage: deploy
#   dependencies:
#     - buildNext # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
#   before_script:
#     - pip install awscli # Install the SDK
#   script:
#     - aws s3 sync out s3://${BUCKET_NAME}/
#   only:
#     - master
